In [1]:
# import libraries
import tensorflow as tf
import pandas as pd
import numpy as np
import sys
import math
%matplotlib inline

print('Python version ' + sys.version)
print('Tensorflow version ' + tf.VERSION)
print('Pandas version ' + pd.__version__)
print('Numpy version ' + np.__version__)

Python version 3.6.1 |Anaconda custom (64-bit)| (default, May 11 2017, 13:09:58) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)]
Tensorflow version 1.2.1
Pandas version 0.20.1
Numpy version 1.12.1


In [2]:
# define the sigmoid function
def sigmoid(x, derivative=False):
    tmp = tf.constant(1)
    if (derivative == True):
        return tf.multiply(x, tf.subtract(1,x))
    else:
        return tf.div(tmp, tf.add(tmp, tf.exp(tf.negative(x))))

In [3]:
np.random.seed(1)

# learning rate
alpha = .1

# number of nodes in the hidden layer
num_hidden = 3

# number of iterations of gradient descent
num_iterations = 100000

# inputs
X = np.array([  
    [0, 0, 1],
    [0, 1, 1],
    [1, 0, 0],
    [1, 1, 0],
    [1, 0, 1],
    [1, 1, 1],
])

print(X)

# outputs
# x.T is the transpose of x, making this a column vector
y = np.array([[0, 1, 0, 1, 1, 0]]).T
print(y)

[[0 0 1]
 [0 1 1]
 [1 0 0]
 [1 1 0]
 [1 0 1]
 [1 1 1]]
[[0]
 [1]
 [0]
 [1]
 [1]
 [0]]


In [7]:
# initialize weights randomly with mean 0 and range [-1, 1]
# the +1 in the 1st dimension of the weight matrices is for the bias weight
hidden_weights = tf.Variable(2*np.random.random((X.shape[1] + 1, num_hidden)) - 1)
output_weights = tf.Variable(2*np.random.random((num_hidden + 1, y.shape[1])) - 1)

In [6]:
# forward phase
# np.hstack((np.ones(...), X) adds a fixed input of 1 for the bias weight
input_layer_outputs = tf.Variable(np.hstack((np.ones((X.shape[0], 1)), X)))
hidden_layer_outputs = tf.Variable(np.hstack((np.ones((X.shape[0], 1)), sigmoid(tf.matmul(input_layer_outputs, tf.transpose(hidden_weights)))))
output_layer_outputs = tf.Variable(tf.matmul(hidden_layer_outputs, tf.transpose(output_weights)))

# backward phase
# output layer error term
output_error = output_layer_outputs - y
# hidden layer error term
# [:, 1:] removes the bias term from the backpropagation
hidden_error = hidden_layer_outputs[:, 1:] * (1 - hidden_layer_outputs[:, 1:]) * np.dot(output_error, output_weights.T[:, 1:])

# partial derivatives
hidden_pd = input_layer_outputs[:, :, np.newaxis] * hidden_error[: , np.newaxis, :]
output_pd = hidden_layer_outputs[:, :, np.newaxis] * output_error[:, np.newaxis, :]

# average for total gradients
total_hidden_gradient = np.average(hidden_pd, axis=0)
total_output_gradient = np.average(output_pd, axis=0)

# update weights
hidden_weights += - alpha * total_hidden_gradient
output_weights += - alpha * total_output_gradient

[[ 1.  0.  0.  1.]
 [ 1.  0.  1.  1.]
 [ 1.  1.  0.  0.]
 [ 1.  1.  1.  0.]
 [ 1.  1.  0.  1.]
 [ 1.  1.  1.  1.]]
